import { useState, useEffect } from 'react';
import { X, Save, Sparkles, Upload, Eye } from 'lucide-react';
import { supabase } from '@/lib/supabase.client';
import { useToast } from './Toast';
import SmartLinkPreview from './SmartLinkPreview';
import { autoGenerateDeepLinks, identifyTrackFromSpotify, type BaseTrack } from '../lib/songFinder';
import { toDeepLink } from '../lib/deepLinks';
import { normalizeAllPlatformUrls, normalizePlatformUrl } from '../lib/platformLinkNormalizer';
import { chargeCredits, InsufficientCreditsError, getWallet } from '../lib/credits';
import InsufficientCreditsModal from './ui/InsufficientCreditsModal';

interface SmartLinkConfig {
  // Smart links use existing column structure
  // No additional config needed
}

interface SmartLinkEditorProps {
  link: {
    id?: string;
    title: string;
    slug: string;
    cover_image_url?: string | null;
    spotify_url?: string | null;
    apple_music_url?: string | null;
    youtube_url?: string | null;
    tidal_url?: string | null;
    soundcloud_url?: string | null;
    source_url?: string | null;
    template?: string;
    color_scheme?: {
      primary: string;
      secondary: string;
      background: string;
      text: string;
    };
  };
  onSave: (link: any) => Promise<void>;
  onCancel: () => void;
}

const templates = [
  { id: 'modern', name: 'Modern', description: 'Clean card-based design' },
  { id: 'classic', name: 'Classic', description: 'Traditional button layout' },
  { id: 'minimal', name: 'Minimal', description: 'Simple and elegant' },
  { id: 'gradient', name: 'Gradient', description: 'Vibrant gradient background' },
];

const colorSchemes = [
  { id: 'blue', name: 'Blue', primary: '#3B82F6', secondary: '#1E40AF', background: '#000000', text: '#FFFFFF' },
  { id: 'green', name: 'Green', primary: '#10B981', secondary: '#059669', background: '#000000', text: '#FFFFFF' },
  { id: 'purple', name: 'Purple', primary: '#8B5CF6', secondary: '#6D28D9', background: '#000000', text: '#FFFFFF' },
  { id: 'red', name: 'Red', primary: '#EF4444', secondary: '#DC2626', background: '#000000', text: '#FFFFFF' },
  { id: 'orange', name: 'Orange', primary: '#F97316', secondary: '#EA580C', background: '#000000', text: '#FFFFFF' },
  { id: 'pink', name: 'Pink', primary: '#EC4899', secondary: '#DB2777', background: '#000000', text: '#FFFFFF' },
  { id: 'light', name: 'Light', primary: '#3B82F6', secondary: '#1E40AF', background: '#FFFFFF', text: '#000000' },
];

export default function SmartLinkEditor({ link, onSave, onCancel }: SmartLinkEditorProps) {
  const { showToast } = useToast();
  const [formData, setFormData] = useState({
    title: link.title || '',
    slug: link.slug || '',
    cover_image_url: link.cover_image_url || '',
    spotify_url: link.spotify_url || '',
    apple_music_url: link.apple_music_url || '',
    youtube_url: link.youtube_url || '',
    tidal_url: link.tidal_url || '',
    soundcloud_url: link.soundcloud_url || '',
    source_url: link.source_url || '',
    template: link.template || 'modern',
    color_scheme: link.color_scheme || colorSchemes[0],
  });
  const [saving, setSaving] = useState(false);
  const [discovering, setDiscovering] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [fetchingArt, setFetchingArt] = useState(false);
  const [autoResolveInput, setAutoResolveInput] = useState('');
  const [deeplinks, setDeeplinks] = useState<{
    spotify?: string | null;
    appleMusic?: string | null;
    youtubeMusic?: string | null;
    tidal?: string | null;
    soundcloud?: string | null;
  }>({});
  const [insufficientModal, setInsufficientModal] = useState<{
    open: boolean;
    cost: number;
    remaining: number;
    featureKey: string;
    plan: string;
  }>({ open: false, cost: 0, remaining: 0, featureKey: '', plan: '' });

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      showToast('Please upload an image file', 'error');
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      showToast('File size must be less than 5MB', 'error');
      return;
    }

    setUploading(true);

    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${Date.now()}.${fileExt}`;
      const filePath = `cover-art/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('cover-art')
        .upload(filePath, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('cover-art')
        .getPublicUrl(filePath);

      setFormData(prev => ({ ...prev, cover_image_url: publicUrl }));
      showToast('Image uploaded successfully!', 'success');
    } catch (error: any) {
      console.error('Upload error:', error);
      showToast('Error uploading image: ' + error.message, 'error');
    } finally {
      setUploading(false);
    }
  };

  // Helper: normalize links from backend response
  const normalizeLinks = (links: Record<string, string>) => {
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(links || {})) {
      if (!v) continue;
      const key = k.toLowerCase();
      if (key.includes('spotify')) out.spotify = v;
      else if (key.includes('apple')) out.apple_music = v;
      else if (key.includes('youtube')) out.youtube = v;
      else if (key.includes('deezer')) out.deezer = v;
      else if (key.includes('tidal')) out.tidal = v;
      else if (key.includes('soundcloud')) out.soundcloud = v;
      else if (key.includes('amazon')) out.amazon_music = v;
      else out[key] = v;
    }
    return out;
  };

  const handleAutoResolveWithAudd = async () => {
    const input = autoResolveInput.trim();

    if (!input) {
      showToast('Paste a Spotify/Apple/YouTube link or type "Artist - Song"', 'warning');
      return;
    }

    setDiscovering(true);

    try {
      const res = await fetch('/.netlify/functions/smartlink-resolve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input }), // Always send non-empty input
      });

      const data = await res.json();

      if (!res.ok || data?.ok === false) {
        console.error('[SmartLink AutoResolve] failed:', data);
        showToast(data?.message || data?.error || 'Auto-resolve failed', 'error');
        setDiscovering(false);
        return;
      }

      // Apply returned metadata to form
      const updates: any = {};

      // Title - only set if current title is empty
      if (data?.title && !formData.title.trim()) {
        updates.title = data.title;
      }

      // Cover art
      if (data?.artwork_url) {
        updates.cover_image_url = data.artwork_url;
      }

      // Platform links
      if (data?.links) {
        const mapped = normalizeLinks(data.links);
        if (mapped.spotify) updates.spotify_url = mapped.spotify;
        if (mapped.apple_music) updates.apple_music_url = mapped.apple_music;
        if (mapped.youtube) updates.youtube_url = mapped.youtube;
        if (mapped.tidal) updates.tidal_url = mapped.tidal;
        if (mapped.soundcloud) updates.soundcloud_url = mapped.soundcloud;
      }

      // ✅ Only count truthy URLs
      const linkCount = Object.values(data?.links || {}).filter(Boolean).length;

      if (linkCount === 0) {
        showToast('No platforms found. Try a different URL or search term.', 'warning');
        setDiscovering(false);
        return;
      }

      setFormData(prev => ({
        ...prev,
        ...updates
      }));

      // Update deep links
      const mappedLinks = data?.links ? normalizeLinks(data.links) : {};
      setDeeplinks({
        spotify: mappedLinks.spotify ? toDeepLink(mappedLinks.spotify, 'spotify') : null,
        appleMusic: mappedLinks.apple_music ? toDeepLink(mappedLinks.apple_music, 'applemusic') : null,
        youtubeMusic: mappedLinks.youtube ? toDeepLink(mappedLinks.youtube, 'youtubemusic') : null,
        tidal: mappedLinks.tidal ? toDeepLink(mappedLinks.tidal, 'tidal') : null,
        soundcloud: mappedLinks.soundcloud ? toDeepLink(mappedLinks.soundcloud, 'soundcloud') : null,
      });

      showToast(`Auto-resolved ${linkCount} platform${linkCount !== 1 ? 's' : ''}!`, 'success');

      // Clear input after successful resolve
      setAutoResolveInput('');
    } catch (err: any) {
      console.error('[SmartLink AutoResolve] error:', err);
      showToast(err.message || 'Auto-resolve failed. Check console logs.', 'error');
    } finally {
      setDiscovering(false);
    }
  };

  const handlePlayNow = () => {
    const available = [
      deeplinks.spotify,
      deeplinks.appleMusic,
      deeplinks.youtubeMusic,
      deeplinks.tidal,
      deeplinks.soundcloud,
    ].find((link) => link);

    if (available) {
      window.open(available, '_blank');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      // Charge credits FIRST
      const featureKey = link.id ? 'smart_link_update' : 'smart_link_create';
      await chargeCredits(featureKey, {
        smart_link_id: link.id,
        slug: formData.slug,
        title: formData.title,
      });

      // THEN normalize and save
      const normalizedData = normalizeAllPlatformUrls(formData);
      await onSave(normalizedData);
    } catch (error: any) {
      if (error instanceof InsufficientCreditsError) {
        const wallet = await getWallet();
        setInsufficientModal({
          open: true,
          cost: error.cost,
          remaining: error.remaining,
          featureKey: error.feature_key,
          plan: wallet?.plan || 'operator',
        });
        setSaving(false);
        return;
      }
      showToast(error?.message || 'Failed to save link', 'error');
    } finally {
      setSaving(false);
    }
  };

  // Auto-normalize platform URL on blur
  const handlePlatformUrlBlur = (platform: string, currentValue: string) => {
    const normalized = normalizePlatformUrl(platform, currentValue);
    if (normalized !== currentValue) {
      const fieldName = `${platform === 'youtube' ? 'youtube' : platform}_url` as keyof typeof formData;
      setFormData({ ...formData, [fieldName]: normalized });
      if (normalized !== currentValue.trim()) {
        showToast(`${platform === 'spotify' ? 'Spotify' : platform === 'apple_music' ? 'Apple Music' : platform === 'youtube' ? 'YouTube' : platform === 'tidal' ? 'Tidal' : 'SoundCloud'} URL auto-formatted`, 'success');
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-gradient-to-b from-ghoste-black/95 via-ghoste-navy/95 to-ghoste-black/95 p-4 backdrop-blur-sm">
      <div className="flex w-full max-w-6xl max-h-[90vh] gap-6 rounded-2xl border border-white/10 bg-gradient-to-b from-ghoste-black/90 via-ghoste-navy/80 to-ghoste-black/90 shadow-[0_24px_80px_rgba(0,0,0,0.9)] backdrop-blur-xl">
        <div className="flex-1 overflow-y-auto p-6">
          <div className="mb-6 flex items-center justify-between">
            <div>
              <h2 className="text-xl font-semibold tracking-tight text-ghoste-white">
                {link.id ? 'Edit Smart Link' : 'Create Smart Link'}
              </h2>
              <p className="text-[11px] text-ghoste-grey mt-1">
                Create a unified link that works across all streaming platforms
              </p>
            </div>
            <button
              type="button"
              onClick={onCancel}
              className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-ghoste-black/70 text-ghoste-grey hover:border-white/20 hover:text-ghoste-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Auto-Resolve Section */}
            <section className="rounded-2xl border border-ghoste-blue/30 bg-gradient-to-br from-ghoste-blue/10 via-ghoste-black/60 to-ghoste-blue/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
              <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-ghoste-white">
                <Sparkles className="h-4 w-4 text-ghoste-blue" />
                Auto-Resolve All Platforms
              </h3>
              <p className="mb-3 text-[11px] text-ghoste-grey">
                Paste a Spotify/Apple/YouTube link OR type "Artist - Song" to auto-fill everything
              </p>
              <div className="space-y-3">
                <input
                  type="text"
                  value={autoResolveInput}
                  onChange={(e) => setAutoResolveInput(e.target.value)}
                  className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                  placeholder="Paste a Spotify/Apple/YouTube link or type Artist - Song"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !discovering) {
                      e.preventDefault();
                      handleAutoResolveWithAudd();
                    }
                  }}
                />

                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={handleAutoResolveWithAudd}
                    disabled={discovering}
                    className="flex flex-1 items-center justify-center gap-2 rounded-full border border-white/10 bg-ghoste-blue px-4 py-3 text-xs font-semibold text-ghoste-white shadow-[0_0_24px_rgba(26,108,255,0.7)] transition hover:bg-ghoste-blue/90 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <Sparkles className="h-5 w-5" />
                    {discovering ? 'Auto-Resolving...' : 'Auto-Resolve'}
                  </button>
                  <button
                    type="button"
                    onClick={handlePlayNow}
                    disabled={!deeplinks.spotify && !deeplinks.appleMusic && !deeplinks.youtubeMusic && !deeplinks.tidal && !deeplinks.soundcloud}
                    className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/10 px-6 py-3 text-xs font-semibold text-ghoste-white transition hover:bg-white/20 disabled:cursor-not-allowed disabled:opacity-50"
                    title="Play on your preferred streaming app"
                  >
                    ▶️ Play Now
                  </button>
                </div>
              </div>
            </section>

            {/* Basic Info */}
            <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
              <h3 className="mb-3 text-sm font-semibold text-ghoste-white">
                Basic Information
              </h3>
              <div className="space-y-3">
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-ghoste-grey">
                    Title *
                  </label>
                  <input
                    type="text"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                    placeholder="My Song Title"
                    required
                  />
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-ghoste-grey">
                    Custom URL (optional)
                  </label>
                  <div className="flex items-stretch gap-2">
                    <span className="inline-flex items-center rounded-xl bg-ghoste-black/80 border border-white/10 px-3 text-xs text-ghoste-grey">
                      ghoste.one/s/
                    </span>
                    <input
                      type="text"
                      value={formData.slug}
                      onChange={(e) =>
                        setFormData({
                          ...formData,
                          slug: e.target.value
                            .toLowerCase()
                            .replace(/\s+/g, '-')
                            .replace(/[^a-z0-9-]/g, '')
                        })
                      }
                      className="flex-1 rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder="my-song (auto-generated if empty)"
                    />
                  </div>
                </div>
              </div>
            </section>

            {/* Cover Image */}
            <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
              <h3 className="mb-3 text-sm font-semibold text-ghoste-white">Cover Artwork</h3>
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-2">
                  <label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-white/10 bg-ghoste-blue px-4 py-3 text-xs font-medium text-ghoste-white shadow-[0_0_18px_rgba(26,108,255,0.6)] transition hover:bg-ghoste-blue/90">
                    <Upload className="h-4 w-4" />
                    {uploading ? 'Uploading...' : 'Upload Image'}
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleFileUpload}
                      disabled={uploading}
                      className="hidden"
                    />
                  </label>
                </div>
                <input
                  type="url"
                  value={formData.cover_image_url}
                  onChange={(e) => setFormData({ ...formData, cover_image_url: e.target.value })}
                  className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                  placeholder="Or paste image URL"
                />
                {formData.cover_image_url && (
                  <img src={formData.cover_image_url} alt="Cover" className="w-24 h-24 rounded-xl border border-white/10 object-cover" />
                )}
              </div>
            </section>

            {/* Platform URLs */}
            <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
              <h3 className="mb-3 text-sm font-semibold text-ghoste-white">Platform Links</h3>
              <div className="space-y-3">
                {[
                  { key: 'spotify_url', label: 'Spotify', platform: 'spotify' },
                  { key: 'apple_music_url', label: 'Apple Music', platform: 'apple_music' },
                  { key: 'youtube_url', label: 'YouTube Music', platform: 'youtube' },
                  { key: 'tidal_url', label: 'Tidal', platform: 'tidal' },
                  { key: 'soundcloud_url', label: 'SoundCloud', platform: 'soundcloud' },
                ].map(({ key, label, platform }) => (
                  <div key={key}>
                    <label className="mb-1.5 block text-xs font-medium text-ghoste-grey">
                      {label}
                    </label>
                    <input
                      type="text"
                      value={(formData as any)[key]}
                      onChange={(e) => setFormData({ ...formData, [key]: e.target.value })}
                      onBlur={(e) => handlePlatformUrlBlur(platform, e.target.value)}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder={`${label} URL${platform === 'spotify' ? ' (or spotify:track:xxx)' : ''}`}
                    />
                  </div>
                ))}
              </div>
            </section>

            {/* Actions */}
            <div className="flex justify-end gap-3 pt-2">
              <button
                type="button"
                onClick={onCancel}
                className="rounded-xl border border-white/10 bg-white/5 px-6 py-2.5 text-sm font-medium text-ghoste-white transition hover:bg-white/8"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={saving || !formData.title.trim()}
                className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-ghoste-blue px-6 py-2.5 text-sm font-medium text-white shadow-[0_0_24px_rgba(26,108,255,0.5)] transition hover:bg-ghoste-blue/90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Save className="w-4 h-4" />
                {saving ? 'Saving...' : link.id ? 'Update Smart Link' : 'Create Smart Link'}
              </button>
            </div>
          </form>
        </div>

        {/* Preview Panel */}
        {showPreview && (
          <div className="w-96 border-l border-white/10 p-6 overflow-y-auto">
            <SmartLinkPreview
              title={formData.title}
              coverImageUrl={formData.cover_image_url}
              spotifyUrl={formData.spotify_url}
              appleMusicUrl={formData.apple_music_url}
              youtubeUrl={formData.youtube_url}
              tidalUrl={formData.tidal_url}
              soundcloudUrl={formData.soundcloud_url}
              template={formData.template}
              colorScheme={formData.color_scheme}
            />
          </div>
        )}
      </div>

      {/* Insufficient Credits Modal */}
      <InsufficientCreditsModal
        isOpen={insufficientModal.open}
        onClose={() => setInsufficientModal({ ...insufficientModal, open: false })}
        cost={insufficientModal.cost}
        remaining={insufficientModal.remaining}
        featureKey={insufficientModal.featureKey}
        plan={insufficientModal.plan}
      />
    </div>
  );
}
