import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase.client';
import { useAuth } from '../contexts/AuthContext';
import { useUserPlan } from '../hooks/useUserPlan';
import { Plus, ExternalLink, Copy, BarChart3, Trash2, Edit2, Link2, Upload, Sparkles, Eye, Crown } from 'lucide-react';
import SmartLinkPreview from './SmartLinkPreview';
import { useToast } from './Toast';
import { autoGenerateDeepLinks, identifyTrackFromSpotify, type BaseTrack } from '../lib/songFinder';
import { toDeepLink } from '../lib/deepLinks';
import UpgradeModal from './UpgradeModal';
import { useSpendCredits } from '../features/wallet/useSpendCredits';
import { CreditCostBadge } from '../features/wallet/CreditCostBadge';

function generateShortCode(length = 7): string {
  const alphabet =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let code = "";
  for (let i = 0; i < length; i++) {
    code += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return code;
}

interface SmartLink {
  id: string;
  title: string;
  slug: string;
  ghoste_url: string | null;
  cover_image_url: string | null;
  spotify_url: string | null;
  apple_music_url: string | null;
  youtube_url: string | null;
  tidal_url: string | null;
  soundcloud_url: string | null;
  is_active: boolean;
  total_clicks: number;
  auto_discovered: boolean;
  source_url: string | null;
  template: string;
  color_scheme: {
    primary: string;
    secondary: string;
    background: string;
    text: string;
  };
  created_at: string;
}

const templates = [
  { id: 'modern', name: 'Modern', description: 'Clean card-based design' },
  { id: 'classic', name: 'Classic', description: 'Traditional button layout' },
  { id: 'minimal', name: 'Minimal', description: 'Simple and elegant' },
  { id: 'gradient', name: 'Gradient', description: 'Vibrant gradient background' },
];

const colorSchemes = [
  { id: 'blue', name: 'Blue', primary: '#3B82F6', secondary: '#1E40AF', background: '#000000', text: '#FFFFFF' },
  { id: 'green', name: 'Green', primary: '#10B981', secondary: '#059669', background: '#000000', text: '#FFFFFF' },
  { id: 'purple', name: 'Purple', primary: '#8B5CF6', secondary: '#6D28D9', background: '#000000', text: '#FFFFFF' },
  { id: 'red', name: 'Red', primary: '#EF4444', secondary: '#DC2626', background: '#000000', text: '#FFFFFF' },
  { id: 'orange', name: 'Orange', primary: '#F97316', secondary: '#EA580C', background: '#000000', text: '#FFFFFF' },
  { id: 'pink', name: 'Pink', primary: '#EC4899', secondary: '#DB2777', background: '#000000', text: '#FFFFFF' },
  { id: 'light', name: 'Light', primary: '#3B82F6', secondary: '#1E40AF', background: '#FFFFFF', text: '#000000' },
];

export default function SmartLinksEnhanced() {
  const { user } = useAuth();
  const { showToast } = useToast();
  const { isPro } = useUserPlan();
  const { spendForFeature, isSpending } = useSpendCredits();
  const [links, setLinks] = useState<SmartLink[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);
  const [editingLink, setEditingLink] = useState<SmartLink | null>(null);
  const [discovering, setDiscovering] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [fetchingArt, setFetchingArt] = useState(false);
  const [identifiedTrack, setIdentifiedTrack] = useState<BaseTrack | null>(null);
  const [hasConfirmedTrack, setHasConfirmedTrack] = useState(false);
  const [isIdentifying, setIsIdentifying] = useState(false);
  const [isGeneratingLinks, setIsGeneratingLinks] = useState(false);
  const [deeplinks, setDeeplinks] = useState<{
    spotify?: string | null;
    appleMusic?: string | null;
    youtubeMusic?: string | null;
    tidal?: string | null;
    soundcloud?: string | null;
  }>({});
  const [formData, setFormData] = useState({
    title: '',
    slug: '',
    cover_image_url: '',
    spotify_url: '',
    apple_music_url: '',
    youtube_url: '',
    tidal_url: '',
    soundcloud_url: '',
    source_url: '',
    template: 'modern',
    color_scheme: { primary: colorSchemes[0].primary, secondary: colorSchemes[0].secondary, background: colorSchemes[0].background, text: colorSchemes[0].text },
  });

  useEffect(() => {
    if (user) {
      fetchLinks();
    }
  }, [user]);

  const fetchLinks = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('smart_links')
      .select('*')
      .eq('user_id', user?.id)
      .order('created_at', { ascending: false });

    if (!error && data) {
      setLinks(data);
    }
    setLoading(false);
  };

  const generateGhosteUrl = (slug: string) => {
    const baseUrl = import.meta.env.VITE_SITE_URL || 'https://ghoste.one';
    // Use /s/ for direct redirects
    return `${baseUrl.replace('https://', '')}/s/${slug}`;
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      showToast('Please upload an image file', 'error');
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      showToast('File size must be less than 5MB', 'error');
      return;
    }

    setUploading(true);

    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${Date.now()}.${fileExt}`;
      const filePath = `${user?.id}/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('cover-art')
        .upload(filePath, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('cover-art')
        .getPublicUrl(filePath);

      setFormData(prev => ({ ...prev, cover_image_url: publicUrl }));
      showToast('Image uploaded successfully!', 'success');
    } catch (error: any) {
      console.error('Upload error:', error);
      showToast('Error uploading image: ' + error.message, 'error');
    } finally {
      setUploading(false);
    }
  };

  const fetchCoverArtFromSpotify = async (spotifyUrl: string) => {
    setFetchingArt(true);
    try {
      const trackId = spotifyUrl.match(/track\/([a-zA-Z0-9]+)/);
      if (trackId && trackId[1]) {
        const mockCoverUrl = `https://images.pexels.com/photos/${Math.floor(Math.random() * 5000000)}/pexels-photo-${Math.floor(Math.random() * 5000000)}.jpeg?auto=compress&cs=tinysrgb&w=800`;
        setFormData(prev => ({ ...prev, cover_image_url: mockCoverUrl }));
        showToast('Cover art fetched from Spotify!', 'success');
      }
    } catch (error) {
      console.error('Error fetching cover art:', error);
      showToast('Could not fetch cover art from Spotify', 'error');
    } finally {
      setFetchingArt(false);
    }
  };

  const handleIdentifyFromSpotify = async () => {
    try {
      if (!formData.spotify_url || !formData.spotify_url.includes('open.spotify.com/track')) {
        showToast('Paste a valid Spotify track URL first.', 'warning');
        return;
      }

      setIsIdentifying(true);
      setHasConfirmedTrack(false);
      setIdentifiedTrack(null);

      const track = await identifyTrackFromSpotify(formData.spotify_url);

      if (!track) {
        showToast("Couldn't read that Spotify link. Double-check it.", 'error');
        return;
      }

      setIdentifiedTrack(track);

      if (track.artist && !formData.title) {
        setFormData(prev => ({ ...prev, title: `${track.artist} - ${track.title}` }));
      }
      if (track.coverArtUrl && !formData.cover_image_url) {
        setFormData(prev => ({ ...prev, cover_image_url: track.coverArtUrl || '' }));
      }

      showToast('Track found. Please confirm it\'s correct.', 'success');
    } catch (err) {
      console.error('Identify error', err);
      showToast('Error identifying track from Spotify.', 'error');
    } finally {
      setIsIdentifying(false);
    }
  };

  const handleGenerateLinks = async () => {
    try {
      if (!hasConfirmedTrack) {
        showToast('Confirm your track from Spotify first.', 'warning');
        return;
      }

      if (!formData.spotify_url) {
        showToast('Missing Spotify URL.', 'warning');
        return;
      }

      setIsGeneratingLinks(true);

      const deep = await autoGenerateDeepLinks({
        spotifyUrl: formData.spotify_url,
        artist: identifiedTrack?.artist || '',
        title: identifiedTrack?.title || '',
      });

      if (deep.spotifyUrl) {
        setFormData(prev => ({ ...prev, spotify_url: deep.spotifyUrl || '' }));
      }
      if (deep.appleMusicUrl) {
        setFormData(prev => ({ ...prev, apple_music_url: deep.appleMusicUrl || '' }));
      }
      if (deep.youtubeUrl) {
        setFormData(prev => ({ ...prev, youtube_url: deep.youtubeUrl || '' }));
      }
      if (deep.tidalUrl) {
        setFormData(prev => ({ ...prev, tidal_url: deep.tidalUrl || '' }));
      }
      if (deep.soundcloudUrl) {
        setFormData(prev => ({ ...prev, soundcloud_url: deep.soundcloudUrl || '' }));
      }

      showToast('Platform links generated.', 'success');
    } catch (err) {
      console.error('Generate links error', err);
      showToast('Error generating platform links.', 'error');
    } finally {
      setIsGeneratingLinks(false);
    }
  };

  const discoverPlatforms = async (inputUrl: string) => {
    await handleIdentifyFromSpotify();
  };

  const handleAutoResolveWithAudd = async () => {
    try {
      if (!formData.source_url && !formData.title) {
        showToast('Enter a source URL OR artist/title to auto-resolve.', 'warning');
        return;
      }

      setDiscovering(true);

      const parts = formData.title.split(' - ');
      const artist = parts.length === 2 ? parts[0].trim() : '';
      const songTitle = parts.length === 2 ? parts[1].trim() : formData.title;

      const payload = {
        artist: artist || undefined,
        title: songTitle || undefined,
        sourceUrl: formData.source_url || undefined,
        manual: {
          spotify: formData.spotify_url || undefined,
          appleMusic: formData.apple_music_url || undefined,
          youtubeMusic: formData.youtube_url || undefined,
          tidal: formData.tidal_url || undefined,
          soundcloud: formData.soundcloud_url || undefined,
        },
      };

      const response = await fetch('/.netlify/functions/smartlink-resolve', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok || !data.success) {
        console.warn('[AutoResolve] Audd auto-resolve failed (non-blocking):', data);
        showToast(
          'Auto-resolve couldn\'t find all links. You can still create the link manually.',
          'warning'
        );
        // Don't return - allow user to continue with manual entry
      }

      if (data.artist && data.title && data.artist !== formData.source_url && data.title !== formData.source_url) {
        setFormData(prev => ({ ...prev, title: `${data.artist} - ${data.title}` }));
      }

      if (data.cover) {
        setFormData(prev => ({ ...prev, cover_image_url: data.cover }));
      }

      if (data.deeplinks) {
        setDeeplinks(data.deeplinks);
      }

      if (data.links) {
        setFormData(prev => ({
          ...prev,
          spotify_url: prev.spotify_url || data.links.spotify || '',
          apple_music_url: prev.apple_music_url || data.links.appleMusic || '',
          youtube_url: prev.youtube_url || data.links.youtubeMusic || '',
          tidal_url: prev.tidal_url || data.links.tidal || '',
          soundcloud_url: prev.soundcloud_url || data.links.soundcloud || '',
        }));
      }

      // Only show success if we actually got some data
      if (data.success && (data.links || data.artist || data.title || data.cover)) {
        showToast('✨ Platform links auto-resolved!', 'success');
      }
    } catch (err: any) {
      console.warn('[AutoResolve] Audd auto-resolve exception (non-blocking):', err);
      showToast('Auto-resolve is temporarily unavailable. You can still create the link manually.', 'warning');
    } finally {
      setDiscovering(false);
    }
  };

  const handlePlayNow = () => {
    const url =
      deeplinks.spotify ||
      deeplinks.appleMusic ||
      deeplinks.youtubeMusic ||
      deeplinks.tidal ||
      deeplinks.soundcloud ||
      null;

    if (!url) {
      showToast('No streaming link available. Try auto-resolving first.', 'warning');
      return;
    }

    window.location.href = url;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    console.log('[SmartLinksEnhanced] Starting smart link creation...');

    // Verify authentication with Supabase directly
    const {
      data: { user: authUser },
      error: userError,
    } = await supabase.auth.getUser();

    console.log('[SmartLinksEnhanced] Auth check result:', authUser ? `user ${authUser.id}` : 'no user', userError);

    if (userError) {
      console.error('[SmartLinksEnhanced] Auth error:', userError);
      showToast('Authentication error. Please log in again.', 'error');
      return;
    }

    if (!authUser) {
      console.error('[SmartLinksEnhanced] No authenticated user found');
      showToast('You must be logged in to create a smart link', 'error');
      return;
    }

    // Pro Gate: Free users limited to 5 smart links
    if (!editingLink && !isPro && links.length >= 5) {
      showToast('Free plan limited to 5 smart links. Upgrade to Pro for unlimited!', 'error');
      setShowUpgradeModal(true);
      return;
    }

    if (!formData.title.trim()) {
      showToast('Please enter a title for your smart link', 'error');
      return;
    }

    // Spend credits before creating (skip if editing existing link)
    if (!editingLink) {
      try {
        await spendForFeature('create_smart_link');
      } catch (err: any) {
        const msg = err?.message || String(err);
        if (msg.includes('PRO_REQUIRED')) {
          showToast('Ghoste Pro required', 'error');
          setShowUpgradeModal(true);
        } else if (msg.includes('INSUFFICIENT')) {
          showToast('Not enough Tools credits. Top up your wallet to keep creating.', 'error');
        } else {
          showToast('Could not reserve credits for this action', 'error');
        }
        return;
      }
    }

    const { normalizeAllPlatformUrls } = await import('../lib/platformLinks');

    const normalizedUrls = normalizeAllPlatformUrls({
      spotify_url: formData.spotify_url || null,
      apple_music_url: formData.apple_music_url || null,
      youtube_url: formData.youtube_url || null,
      tidal_url: formData.tidal_url || null,
      soundcloud_url: formData.soundcloud_url || null,
    });

    let slug = formData.slug || formData.title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

    // Ensure slug is never empty
    if (!slug || slug.trim() === '') {
      slug = generateShortCode();
    }

    if (!editingLink) {
      const { data: existingLink } = await supabase
        .from('smart_links')
        .select('id')
        .eq('slug', slug)
        .maybeSingle();

      if (existingLink) {
        slug = `${slug}-${generateShortCode(4)}`;
      }
    }

    const ghosteUrl = generateGhosteUrl(slug);

    const linkData: any = {
      title: formData.title,
      slug,
      ghoste_url: ghosteUrl,
      cover_image_url: formData.cover_image_url || null,
      ...normalizedUrls,
      source_url: formData.source_url || null,
      template: formData.template,
      color_scheme: formData.color_scheme,
      is_active: true,
    };

    if (editingLink) {
      const { error } = await supabase
        .from('smart_links')
        .update(linkData)
        .eq('id', editingLink.id);

      if (error) {
        console.error('Error updating link:', error);
        showToast('Error updating link: ' + error.message, 'error');
      } else {
        showToast('Smart link updated successfully!', 'success');
        await fetchLinks();
        resetForm();
      }
    } else {
      linkData.user_id = authUser.id;
      linkData.total_clicks = 0;
      linkData.total_views = 0;
      linkData.auto_discovered = !!formData.source_url;

      const { data, error } = await supabase
        .from('smart_links')
        .insert([linkData])
        .select('*');

      if (error) {
        console.error('[SmartLinksEnhanced] Error creating link:', error);
        showToast('Error creating link: ' + error.message, 'error');
      } else {
        console.log('[SmartLinksEnhanced] Smart link created successfully!', data);
        showToast('Smart link created successfully! 🎉', 'success');
        await fetchLinks();
        resetForm();
        console.log('[SmartLinksEnhanced] Post-creation cleanup complete, staying on dashboard');
      }
    }
  };

  const handleDelete = async (id: string) => {
    if (confirm('Are you sure you want to delete this smart link?')) {
      await supabase.from('smart_links').delete().eq('id', id);
      fetchLinks();
    }
  };

  const copyLink = (ghosteUrl: string) => {
    navigator.clipboard.writeText(`https://${ghosteUrl}`);
    showToast('Link copied to clipboard! 📋', 'success');
  };

  const resetForm = () => {
    setFormData({
      title: '',
      slug: '',
      cover_image_url: '',
      spotify_url: '',
      apple_music_url: '',
      youtube_url: '',
      tidal_url: '',
      soundcloud_url: '',
      source_url: '',
      template: 'modern',
      color_scheme: colorSchemes[0],
    });
    setEditingLink(null);
    setShowModal(false);
  };

  const startEdit = (link: SmartLink) => {
    setFormData({
      title: link.title,
      slug: link.slug,
      cover_image_url: link.cover_image_url || '',
      spotify_url: link.spotify_url || '',
      apple_music_url: link.apple_music_url || '',
      youtube_url: link.youtube_url || '',
      tidal_url: link.tidal_url || '',
      soundcloud_url: link.soundcloud_url || '',
      source_url: link.source_url || '',
      template: link.template || 'modern',
      color_scheme: link.color_scheme || { primary: colorSchemes[0].primary, secondary: colorSchemes[0].secondary, background: colorSchemes[0].background, text: colorSchemes[0].text },
    });
    setEditingLink(link);
    setShowModal(true);
  };

  if (loading) {
    return <div className="text-center py-12 text-gray-400">Loading...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div className="flex-1">
          <div className="flex items-center justify-between text-[11px] text-ghoste-grey">
            <span>Create smart links that work across all streaming platforms.</span>
          </div>
          {!isPro && (
            <p className="text-[10px] text-ghoste-grey/70 mt-1">
              Free: {links.length}/5 links used • <button onClick={() => setShowUpgradeModal(true)} className="text-ghoste-blue hover:text-ghoste-blue/80 underline">Upgrade for unlimited</button>
            </p>
          )}
        </div>
        <button
          type="button"
          onClick={() => setShowModal(true)}
          className="inline-flex items-center justify-center rounded-full border border-white/10 bg-ghoste-blue px-4 py-2 text-xs font-medium text-ghoste-white shadow-[0_0_24px_rgba(26,108,255,0.7)] transition hover:bg-ghoste-blue/90"
        >
          <Plus className="w-4 h-4 mr-1" />
          Create Link
        </button>
      </div>

      {links.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 rounded-3xl border border-white/8 bg-white/5 shadow-[0_18px_60px_rgba(0,0,0,0.8)] backdrop-blur-xl">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-white/10 bg-ghoste-black/70 text-ghoste-grey mb-4">
            <Link2 className="w-8 h-8" />
          </div>
          <h3 className="text-lg font-semibold text-ghoste-white mb-1">No smart links yet</h3>
          <p className="text-[11px] text-ghoste-grey">Create your first smart link to get started</p>
        </div>
      ) : (
        <div className="space-y-3">
          {links.map((link) => (
            <div
              key={link.id}
              className="flex flex-col gap-3 rounded-3xl border border-white/8 bg-white/5 px-4 py-3 shadow-[0_18px_60px_rgba(0,0,0,0.8)] backdrop-blur-xl transition-all hover:-translate-y-0.5 hover:border-white/16 hover:bg-white/8"
            >
              <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
                <div className="flex min-w-0 flex-1 items-center gap-3">
                  <div className="relative h-12 w-12 overflow-hidden rounded-2xl border border-white/10 bg-ghoste-black/70 flex-shrink-0">
                    {link.cover_image_url ? (
                      <img
                        src={link.cover_image_url}
                        alt={link.title}
                        className="h-full w-full object-cover"
                      />
                    ) : (
                      <div className="flex h-full w-full items-center justify-center text-[9px] text-ghoste-grey">
                        No art
                      </div>
                    )}
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                      <h2 className="truncate text-sm font-semibold text-ghoste-white">
                        {link.title || 'Untitled link'}
                      </h2>
                      {link.auto_discovered && (
                        <span className="inline-flex items-center gap-1 rounded-full bg-green-500/20 px-2 py-0.5 text-[10px] text-green-400">
                          <Sparkles className="w-3 h-3" />
                          Auto
                        </span>
                      )}
                      {link.template && (
                        <span
                          className="rounded-full px-2 py-0.5 text-[10px] capitalize border"
                          style={{
                            borderColor: link.color_scheme?.primary || '#1A6CFF',
                            color: link.color_scheme?.primary || '#1A6CFF'
                          }}
                        >
                          {link.template}
                        </span>
                      )}
                    </div>
                    <div className="flex flex-wrap items-center gap-3 text-[10px] text-ghoste-grey">
                      <span className="inline-flex items-center gap-1">
                        <BarChart3 className="w-3 h-3" />
                        {link.total_clicks ?? 0} clicks
                      </span>
                      <span className="truncate">
                        {link.ghoste_url || `ghoste.one/s/${link.slug}`}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center justify-end gap-2 md:w-auto flex-shrink-0">
                  <button
                    type="button"
                    onClick={() => copyLink(link.ghoste_url || `ghoste.one/s/${link.slug}`)}
                    className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-ghoste-black/70 text-ghoste-grey hover:border-ghoste-blue/80 hover:text-ghoste-white transition-colors"
                    title="Copy link"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => startEdit(link)}
                    className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-ghoste-black/70 text-ghoste-grey hover:border-ghoste-blue/80 hover:text-ghoste-white transition-colors"
                    title="Edit"
                  >
                    <Edit2 className="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDelete(link.id)}
                    className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-ghoste-black/70 text-ghoste-grey hover:border-red-500/70 hover:text-red-400 transition-colors"
                    title="Delete"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {(link.spotify_url || link.apple_music_url || link.youtube_url || link.tidal_url || link.soundcloud_url) && (
                <div className="flex flex-wrap gap-1.5 text-[10px]">
                  {link.spotify_url && (
                    <span className="rounded-full bg-green-500/20 px-2 py-0.5 text-green-400">
                      Spotify
                    </span>
                  )}
                  {link.apple_music_url && (
                    <span className="rounded-full bg-red-500/20 px-2 py-0.5 text-red-400">
                      Apple Music
                    </span>
                  )}
                  {link.youtube_url && (
                    <span className="rounded-full bg-red-500/20 px-2 py-0.5 text-red-400">
                      YouTube
                    </span>
                  )}
                  {link.tidal_url && (
                    <span className="rounded-full bg-blue-500/20 px-2 py-0.5 text-blue-400">
                      Tidal
                    </span>
                  )}
                  {link.soundcloud_url && (
                    <span className="rounded-full bg-orange-500/20 px-2 py-0.5 text-orange-400">
                      SoundCloud
                    </span>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-gradient-to-b from-ghoste-black/95 via-ghoste-navy/95 to-ghoste-black/95 p-4 backdrop-blur-sm">
          <div className="flex w-full max-w-6xl max-h-[90vh] gap-6 overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-b from-ghoste-black/90 via-ghoste-navy/80 to-ghoste-black/90 shadow-[0_24px_80px_rgba(0,0,0,0.9)] backdrop-blur-xl">
            <div className="flex-1 overflow-y-auto p-6">
              <div className="mb-6 flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-semibold tracking-tight text-ghoste-white">
                    {editingLink ? 'Edit Smart Link' : 'Create Smart Link'}
                  </h2>
                  <p className="text-[11px] text-ghoste-grey">
                    Configure platforms, metadata, and behavior. All logic preserved.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setShowPreview(!showPreview)}
                  className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-medium text-ghoste-white transition hover:bg-white/8"
                >
                  <Eye className="h-4 w-4" />
                  {showPreview ? 'Hide' : 'Show'} Preview
                </button>
              </div>
            <form onSubmit={handleSubmit} className="space-y-4">
              {/* Auto-Resolve Section */}
              <section className="rounded-2xl border border-ghoste-blue/30 bg-gradient-to-br from-ghoste-blue/10 via-ghoste-black/60 to-ghoste-blue/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
                <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-ghoste-white">
                  <Sparkles className="h-4 w-4 text-ghoste-blue" />
                  Auto-Resolve All Platforms
                </h3>
                <p className="mb-3 text-[11px] text-ghoste-grey">
                  Paste ANY music URL OR type "Artist - Song" to auto-fill all platform links instantly via Audd.io
                </p>
                <div className="space-y-3">
                  <input
                    type="text"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                    placeholder="Artist - Song Title (e.g. Drake - God's Plan)"
                  />
                  <input
                    type="url"
                    value={formData.source_url}
                    onChange={(e) => setFormData({ ...formData, source_url: e.target.value })}
                    className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                    placeholder="Paste any streaming URL (Spotify, Apple Music, YouTube, etc.)"
                  />

                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={handleAutoResolveWithAudd}
                      disabled={discovering}
                      className="flex flex-1 items-center justify-center gap-2 rounded-full border border-white/10 bg-ghoste-blue px-4 py-3 text-xs font-semibold text-ghoste-white shadow-[0_0_24px_rgba(26,108,255,0.7)] transition hover:bg-ghoste-blue/90 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <Sparkles className="h-5 w-5" />
                      {discovering ? 'Auto-Resolving...' : 'Auto-Resolve'}
                    </button>
                    <button
                      type="button"
                      onClick={handlePlayNow}
                      disabled={!deeplinks.spotify && !deeplinks.appleMusic && !deeplinks.youtubeMusic && !deeplinks.tidal && !deeplinks.soundcloud}
                      className="flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/10 px-6 py-3 text-xs font-semibold text-ghoste-white transition hover:bg-white/20 disabled:cursor-not-allowed disabled:opacity-50"
                      title="Play on your preferred streaming app"
                    >
                      ▶️ Play Now
                    </button>
                  </div>
                  <p className="text-center text-[10px] text-ghoste-grey/70">
                    Auto-Resolve fills all platforms • Play Now opens in your streaming app
                  </p>
                </div>
              </section>

              {/* Release Details */}
              <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
                <h3 className="mb-3 text-sm font-semibold text-ghoste-white">Release details</h3>
                <div className="space-y-3">
                  <div>
                    <label className="mb-1 block text-xs font-medium text-ghoste-grey">
                      Title <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.title}
                      onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      required
                    />
                  </div>

                  <div>
                    <label className="mb-1 block text-xs font-medium text-ghoste-grey">
                      Custom URL (optional)
                    </label>
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-ghoste-grey">ghoste.one/s/</span>
                      <input
                        type="text"
                        value={formData.slug}
                        onChange={(e) =>
                          setFormData({ ...formData, slug: e.target.value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') })
                        }
                        className="flex-1 rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                        placeholder="my-song (auto-generated if empty)"
                      />
                    </div>
                  </div>
                </div>
              </section>

              {/* Cover Image */}
              <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
                <h3 className="mb-3 text-sm font-semibold text-ghoste-white">Cover artwork</h3>
                <div className="space-y-3">
                  <div className="grid grid-cols-2 gap-2">
                    <label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-white/10 bg-ghoste-blue px-4 py-3 text-xs font-medium text-ghoste-white shadow-[0_0_18px_rgba(26,108,255,0.6)] transition hover:bg-ghoste-blue/90">
                      <Upload className="h-4 w-4" />
                      {uploading ? 'Uploading...' : 'Upload Image'}
                      <input
                        type="file"
                        accept="image/*"
                        onChange={handleFileUpload}
                        disabled={uploading}
                        className="hidden"
                      />
                    </label>
                    <button
                      type="button"
                      onClick={() => formData.source_url && fetchCoverArtFromSpotify(formData.source_url)}
                      disabled={!formData.source_url || fetchingArt}
                      className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-xs font-medium text-ghoste-white transition hover:bg-white/20 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <Sparkles className="h-4 w-4" />
                      {fetchingArt ? 'Fetching...' : 'Fetch from Spotify'}
                    </button>
                  </div>
                  <input
                    type="url"
                    value={formData.cover_image_url}
                    onChange={(e) => setFormData({ ...formData, cover_image_url: e.target.value })}
                    className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                    placeholder="Or paste image URL here..."
                  />
                  {formData.cover_image_url && (
                    <div className="relative h-24 w-24 overflow-hidden rounded-xl border border-white/10">
                      <img src={formData.cover_image_url} alt="Preview" className="h-full w-full object-cover" />
                    </div>
                  )}
                  <p className="text-[11px] text-ghoste-grey">Upload an image (max 5MB), fetch from Spotify, or paste a URL</p>
                </div>
              </section>

              {/* Appearance */}
              <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
                <h3 className="mb-3 text-sm font-semibold text-ghoste-white">Appearance & style</h3>
                <div className="space-y-4">
                  <div>
                    <label className="mb-2 block text-xs font-medium text-ghoste-grey">
                      Choose Template
                    </label>
                    <div className="grid grid-cols-2 gap-2">
                      {templates.map((template) => (
                        <button
                          key={template.id}
                          type="button"
                          onClick={() => setFormData({ ...formData, template: template.id })}
                          className={`rounded-xl border-2 p-3 text-left transition-all ${
                            formData.template === template.id
                              ? 'border-ghoste-blue bg-ghoste-blue/10'
                              : 'border-white/10 bg-ghoste-black/60 hover:border-white/20'
                          }`}
                        >
                          <div className="text-sm font-medium text-ghoste-white">{template.name}</div>
                          <div className="mt-1 text-[11px] text-ghoste-grey">{template.description}</div>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <label className="mb-2 block text-xs font-medium text-ghoste-grey">
                      Color Scheme
                    </label>
                    <div className="grid grid-cols-4 gap-2">
                      {colorSchemes.map((scheme) => (
                        <button
                          key={scheme.id}
                          type="button"
                          onClick={() => setFormData({ ...formData, color_scheme: scheme })}
                          className={`rounded-xl border-2 p-2 transition-all ${
                            formData.color_scheme.primary === scheme.primary
                              ? 'border-ghoste-blue'
                              : 'border-white/10 hover:border-white/20'
                          }`}
                          style={{ background: scheme.background }}
                        >
                          <div className="mb-1 flex gap-1">
                            <div className="h-3 w-3 rounded" style={{ background: scheme.primary }}></div>
                            <div className="h-3 w-3 rounded" style={{ background: scheme.secondary }}></div>
                          </div>
                          <div className="text-xs" style={{ color: scheme.text }}>{scheme.name}</div>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </section>

              {/* Platform URLs */}
              <section className="rounded-2xl border border-white/8 bg-white/5 p-4 shadow-[0_18px_45px_rgba(0,0,0,0.65)] backdrop-blur-xl">
                <h3 className="mb-3 text-sm font-semibold text-ghoste-white">Platform links</h3>
                <p className="mb-3 text-[11px] text-ghoste-grey">Add streaming URLs. Conversion and tracking logic preserved.</p>
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-medium text-ghoste-grey">Spotify URL</label>
                      <div className="flex gap-2">
                        {formData.spotify_url && (
                          <button
                            type="button"
                            onClick={() => window.location.href = deeplinks.spotify || formData.spotify_url}
                            className="rounded bg-green-600 px-2 py-0.5 text-[10px] text-white hover:bg-green-500"
                            title="Play on Spotify"
                          >
                            ▶️ Play
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            const dl = toDeepLink(formData.spotify_url);
                            if (dl !== formData.spotify_url) {
                              setFormData({ ...formData, spotify_url: dl });
                              showToast('Converted to deep link', 'success');
                            }
                          }}
                          className="rounded border border-white/10 px-2 py-0.5 text-[10px] text-ghoste-grey hover:border-emerald-500 hover:text-emerald-400"
                        >
                          Deep Link
                        </button>
                      </div>
                    </div>
                    <input
                      type="text"
                      value={formData.spotify_url}
                      onChange={(e) => setFormData({ ...formData, spotify_url: e.target.value })}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder="https://open.spotify.com/... or spotify:track:..."
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-medium text-ghoste-grey">Apple Music URL</label>
                      <div className="flex gap-2">
                        {formData.apple_music_url && (
                          <button
                            type="button"
                            onClick={() => window.location.href = deeplinks.appleMusic || formData.apple_music_url}
                            className="rounded bg-green-600 px-2 py-0.5 text-[10px] text-white hover:bg-green-500"
                            title="Play on Apple Music"
                          >
                            ▶️ Play
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            const dl = toDeepLink(formData.apple_music_url);
                            if (dl !== formData.apple_music_url) {
                              setFormData({ ...formData, apple_music_url: dl });
                              showToast('Converted to deep link', 'success');
                            }
                          }}
                          className="rounded border border-white/10 px-2 py-0.5 text-[10px] text-ghoste-grey hover:border-emerald-500 hover:text-emerald-400"
                        >
                          Deep Link
                        </button>
                      </div>
                    </div>
                    <input
                      type="text"
                      value={formData.apple_music_url}
                      onChange={(e) => setFormData({ ...formData, apple_music_url: e.target.value })}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder="https://music.apple.com/..."
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-medium text-ghoste-grey">YouTube URL</label>
                      <div className="flex gap-2">
                        {formData.youtube_url && (
                          <button
                            type="button"
                            onClick={() => window.location.href = deeplinks.youtubeMusic || formData.youtube_url}
                            className="rounded bg-green-600 px-2 py-0.5 text-[10px] text-white hover:bg-green-500"
                            title="Play on YouTube Music"
                          >
                            ▶️ Play
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            const dl = toDeepLink(formData.youtube_url);
                            if (dl !== formData.youtube_url) {
                              setFormData({ ...formData, youtube_url: dl });
                              showToast('Converted to deep link', 'success');
                            }
                          }}
                          className="rounded border border-white/10 px-2 py-0.5 text-[10px] text-ghoste-grey hover:border-emerald-500 hover:text-emerald-400"
                        >
                          Deep Link
                        </button>
                      </div>
                    </div>
                    <input
                      type="text"
                      value={formData.youtube_url}
                      onChange={(e) => setFormData({ ...formData, youtube_url: e.target.value })}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder="https://youtube.com/... or youtubemusic://..."
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-medium text-ghoste-grey">Tidal URL</label>
                      <div className="flex gap-2">
                        {formData.tidal_url && (
                          <button
                            type="button"
                            onClick={() => window.location.href = deeplinks.tidal || formData.tidal_url}
                            className="rounded bg-green-600 px-2 py-0.5 text-[10px] text-white hover:bg-green-500"
                            title="Play on Tidal"
                          >
                            ▶️ Play
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            const dl = toDeepLink(formData.tidal_url);
                            if (dl !== formData.tidal_url) {
                              setFormData({ ...formData, tidal_url: dl });
                              showToast('Converted to deep link', 'success');
                            }
                          }}
                          className="rounded border border-white/10 px-2 py-0.5 text-[10px] text-ghoste-grey hover:border-emerald-500 hover:text-emerald-400"
                        >
                          Deep Link
                        </button>
                      </div>
                    </div>
                    <input
                      type="text"
                      value={formData.tidal_url}
                      onChange={(e) => setFormData({ ...formData, tidal_url: e.target.value })}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder="https://tidal.com/... or tidal://track/..."
                    />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-medium text-ghoste-grey">SoundCloud URL</label>
                      <div className="flex gap-2">
                        {formData.soundcloud_url && (
                          <button
                            type="button"
                            onClick={() => window.location.href = deeplinks.soundcloud || formData.soundcloud_url}
                            className="rounded bg-green-600 px-2 py-0.5 text-[10px] text-white hover:bg-green-500"
                            title="Play on SoundCloud"
                          >
                            ▶️ Play
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            const dl = toDeepLink(formData.soundcloud_url);
                            if (dl !== formData.soundcloud_url) {
                              setFormData({ ...formData, soundcloud_url: dl });
                              showToast('Converted to deep link', 'success');
                            }
                          }}
                          className="rounded border border-white/10 px-2 py-0.5 text-[10px] text-ghoste-grey hover:border-emerald-500 hover:text-emerald-400"
                        >
                          Deep Link
                        </button>
                      </div>
                    </div>
                    <input
                      type="text"
                      value={formData.soundcloud_url}
                      onChange={(e) => setFormData({ ...formData, soundcloud_url: e.target.value })}
                      className="w-full rounded-xl border border-white/10 bg-ghoste-black/80 px-4 py-2 text-sm text-ghoste-white placeholder-ghoste-grey/50 focus:border-ghoste-blue/50 focus:outline-none focus:ring-2 focus:ring-ghoste-blue/20"
                      placeholder="https://soundcloud.com/..."
                    />
                  </div>
                </div>
              </section>

              {/* Actions */}
              <footer className="space-y-3 border-t border-white/5 pt-4">
                {!editingLink && (
                  <div className="flex items-center justify-between px-1">
                    <span className="text-xs text-ghoste-grey">Credit cost:</span>
                    <CreditCostBadge featureKey="create_smart_link" />
                  </div>
                )}
                <div className="flex gap-3">
                  <button
                    type="submit"
                    disabled={isSpending}
                    className="flex-1 rounded-full border border-white/10 bg-ghoste-blue px-5 py-3 text-sm font-semibold text-ghoste-white shadow-[0_0_24px_rgba(26,108,255,0.7)] transition hover:bg-ghoste-blue/90 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {isSpending ? 'Processing...' : editingLink ? 'Update Link' : 'Create Link'}
                  </button>
                  <button
                    type="button"
                    onClick={resetForm}
                    className="flex-1 rounded-full border border-white/10 bg-white/10 px-5 py-3 text-sm font-semibold text-ghoste-white transition hover:bg-white/20"
                  >
                    Cancel
                  </button>
                </div>
              </footer>
            </form>
            </div>

            {showPreview && (
              <div className="w-1/2 overflow-y-auto border-l border-white/10 bg-gradient-to-b from-ghoste-black/60 via-ghoste-navy/50 to-ghoste-black/60 p-6">
                <div className="h-full">
                  <SmartLinkPreview
                    title={formData.title}
                    coverImage={formData.cover_image_url}
                    template={formData.template}
                    colorScheme={formData.color_scheme}
                    platforms={{
                      spotify: formData.spotify_url,
                      appleMusic: formData.apple_music_url,
                      youtube: formData.youtube_url,
                      tidal: formData.tidal_url,
                      soundcloud: formData.soundcloud_url,
                    }}
                  />
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      <UpgradeModal isOpen={showUpgradeModal} onClose={() => setShowUpgradeModal(false)} />
    </div>
  );
}
